apiVersion: v1
kind: Pod
metadata:
  name: crashtest
  namespace: default
  labels:
    app: crashtest
spec:
  restartPolicy: Always
  containers:
  - name: crashtest
    image: busybox:latest
    command: ["sh", "-c", "echo 'crashing intentionally'; exit 1"]
